### ISSUE TITLE
Does RangeEntry represent "No Consent" or the opposite of default consent?

### ISSUE THREAD

**Issue by wangwalton** [LiveRamp/iabconsent#13]
https://github.com/LiveRamp/iabconsent/blob/de5fda813949da3dcc3c2a04cc6a2cfb58cb014d/parsed_consent.go#L43

https://github.com/LiveRamp/iabconsent/blob/de5fda813949da3dcc3c2a04cc6a2cfb58cb014d/v2_parsed_consent.go#L81

There's a difference across version 1 & 2, is this the expected behavior across the version udpate?

**Comment by adayNU** [comment]
Per the [1.1 spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#vendor-consent-string-format-) the `RangeSection` has a field `DefaultConsent`:

> Default consent for VendorIds not covered by a RangeEntry. VendorIds covered by a RangeEntry have a consent value the opposite of DefaultConsent.

Per the [2.0 spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-core-string) they removed the `DefaultConsent` bit from the `RangeSection`, and instead, only vendor IDs (or ranges) listed have received consent. Per the spec on `RangeEntry`:

> A single or range of Vendor ID(s) who have received consent. If a Vendor ID is not within the bounds of the ranges then the vendor is assumed to have “No Consent”.

**Comment by adayNU** [comment]
Going to close, but feel free to comment if you've found something incorrect here!
